name: public
named: {}
views: {}
collections: {}
routes:
  eurocanuck/eggnog.login: true
files: {}
bots: {}
integrationActions: {}
allowallbots: true
allowallcollections: true
allowallviews: true
allowallroutes: true
allowallfiles: true
allowallintegrationactions: true
modifyallrecords: true
viewallrecords: true
